name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    name: Lint / Format / Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Clang-Format + Clang-Tidy combined linter
      - name: Run cpp-linter (clang-format + clang-tidy)
        uses: cpp-linter/cpp-linter-action@v2
        with:
          style: llvm            # use default LLVM formatting
          tidy-checks: '*'       # run default clang-tidy checks
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_test:
    name: Build & Test (${{ matrix.os }})
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libglfw3-dev libx11-dev libxrandr-dev libxi-dev gcovr

      - name: Configure CMake
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
          else
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash

      - name: Build
        run: cmake --build build --config ${{ runner.os == 'Linux' && 'Debug' || 'Release' }}

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -C ${{ runner.os == 'Linux' && 'Debug' || 'Release' }}

      - name: Generate and Check Coverage (Linux)
        if: runner.os == 'Linux'
        run: |
          gcovr -r .. --fail-under-line 80 --exclude-directories "Tests|Dependencies" --print-summary
